## Alacritty Dark Theme (Catppuccin Mocha inspired)
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#cdd6f4"

[colors.normal]
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#bac2de"

[colors.bright]
black   = "#585b70"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#a6adc8"

[font]

[font.normal]
family = "Iosevka Term"
style = "Regular"

[font.bold]
family = "Iosevka Term"
style = "Bold"

[font.italic]
family = "Iosevka Term"
style = "Italic"


[window]
opacity = 0.8 
padding = { x = 4, y = 4 }   # x=左右同时生效；y=上下同时生效
dynamic_padding = true   